🤖 Merge PR #61199 [verror]: Fix `@types/verror` to work with `es2022.error` on TS `4.8` by @voxpelli
This commit fixes the following error, which appears when running TS `^4.8.0-dev.20220707` with eg. ` npx tsc --lib es2020,es2022.error,es2021.promise` or ` npx tsc --lib esnext`

> error TS2425: Class 'Error' defines instance member property 'cause', but extended class 'VError' defines it as instance member function.

Discovered in https://github.com/voxpelli/pony-cause/pull/41 when looking to extend the tests for https://github.com/voxpelli/pony-cause/issues/35 to detect whether the nightly of `4.8.0` now correctly fixes that, following the merge of https://github.com/microsoft/TypeScript/pull/49639